name: flutter_currency_app
description: A currency exchange app made with flutter.
version: 0.0.3
author: Daniel Guerreiro<dfsguer@gmail.com>

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.7
  shared_preferences: ^0.4.2
  page_view_indicator: ^0.3.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^3.0.0
  flutter_launcher_icons: ^0.6.1


flutter:
  uses-material-design: true
  assets:
  - assets/intro/different_currencies.png
  - assets/intro/exchange.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"